Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/09/2021
Var
   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Fimalgoritmo